### ISSUE TITLE
ドラフト【 UI 】[Priority]ラベルとコントロール部分のコンポーネント作成

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#10]
## 実装内容の説明
- priorityコントロール部分作成(UIのみ)
- priorityラベルコンポーネント（High・Middle・Law）の作成(UIのみ)
- priorityコンポーネントとしてまとめておく

## TASK
- [ ] priorityコントロール部分作成(UIのみ)
- [ ] priorityラベルコンポーネント（High・Middle・Law）の作成(UIのみ)

## その他・備考
-

**Comment by Junkichi89** [comment]
> priorityコントロール部分作成(UIのみ)
> priorityラベルコンポーネント（High・Middle・Law）の作成(UIのみ)
> priorityコンポーネントとしてまとめておく

コンポーネントは1つという想定で大丈夫でしょうか？
もう少し抽象的に書くか、より具体的にわかりやすい画像で指摘を入れるかしてもらえるといいかと思います。
