### ISSUE TITLE
ドラフト【 UI 】[Status]ラベルとコントロール部分のコンポーネント作成

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#11]
## 実装内容の説明
- statusのコントロール部分の作成(UIのみ)
- statusラベル（未着手・進行中・完了）の作成（UIのみ）
- statusコンポーネントとしてまとめておく

## TASK
- [ ] statusのコントロール部分の作成(UIのみ)
- [ ] statusラベル（未着手・進行中・完了）の作成（UIのみ）

## その他・備考
-

**Comment by Junkichi89** [comment]
> statusのコントロール部分の作成(UIのみ)
> statusラベル（未着手・進行中・完了）の作成（UIのみ）
> statusコンポーネントとしてまとめておく

コンポーネントは1つという想定で大丈夫でしょうか？
もう少し抽象的に書くか、より具体的にわかりやすい画像で指摘を入れるかしてもらえるといいかと思います。
