### ISSUE TITLE
【 UI 】[ Detail (詳細) ] [ コメントのモーダル ]コンポーネントの作成

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#24]
## 実装内容の説明
- 以下画像の赤枠部分の「コメントのモーダル」のUIの作成をお願いいたします。
機能の実装は別Issueとなりますので、実装不要です。
- テストファイルを作成してください。詳細は下記タスク確認

## 実装予定のページ・コンポーネントのデザイン画像もしくはURL
- https://www.figma.com/file/yIJYguhG5IO8A3VaTHUDOK/Todo?node-id=37%3A678

![comment-modal](https://user-images.githubusercontent.com/57102971/148226830-713c0093-e3fc-438b-b682-7da1cb34dada.png)

## TASK
- [ ]  画像赤枠部分のコンポーネントの実装をお願いします。
- [ ]  pages配下にtest.jsxファイルを作成し、開発したコンポーネントの表示が確認できるように設定してください。

## その他・備考
-

**Comment by mihomihouk** [comment]
マージしたので、closeします！
