### ISSUE TITLE
【 ディレクトリ構成 】最適なディレクトリ構成を考える

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#41]
## 概要

- 現在(1/11)、チームの何人かの間で、暫定的になのですが、一旦Atomicデザインを採用する認識になっています。
フォルダへの分け方が難しいなどありましたら、その都度改善する方向でいいかと思います。

簡単にatomicデザインを紹介すると

- atoms ・・・ボタン、ラベルなど分解できない小さなパーツ
- molecules・・・ボタン＋アルファの複数で組み合わされた中間サイズのパーツ
例）検索バー ＋ 検索ボタンのような構成
- organisms・・・ヘッダーレベルのような、moleculeを複数組み合わせた大きなパーツ
- templates・・・使い回しをするページのテンプレート
※こちら、必要があれば作成する程度のディレクトリという認識なので、初期はディレクトリを作成しません。
- pages・・・ページそのもの

上記のような認識でおります。
今回はプロジェクトの目的上、あまり厳密にコンポーネントを上記のディレクトリへ分けるような形でなく、各担当者の方の感覚で悩まずに、さっと分けてしまってもいいかもしれません。

### 参考URL　どういうわけかURLが大きく表示されてしまいます、申し訳ないです。
https://zenn.dev/sterashima78/articles/0cf4bb52112c7b
https://tech-blog.cloud-config.jp/2021-08-02-what-is-the-atomic-design/
https://atomicdesign.bradfrost.com/chapter-2/
==================================================================

- 担当者それぞれディレクトリ構成を検討していると思いますが、次回MTG( 1/15頃 )で認識合わせをしたいと思っております。
- 現状考えられる構成は以下になります。

1. atomicデザイン (例) src/components/atoms/ atomレベルのコンポーネント
→　粒度の認識が担当者によって変わるので難しめです。ボタン=atomでも、そのボタンの状態により、atomとは考えない方もいる可能性があります。
2. src/components/コンポーネントをページごとにまとめるフォルダ/ページごとのコンポーネント
3. src/components/layouts..など機能・用途ごとにコンポーネントをまとめる
etc..
- そのほかにも色々な考え方があるかと思いますので、こちらのIssue内で意見出し合えればと思います。

## TASK
- [ ] 
- [ ] 
- [ ] 

## その他・備考
-

**Comment by insideplant** [comment]
私の方はatomicデザインでのコンポーネント管理しか知識無いので、そちらで問題ないです！
他のコンポーネント管理方法もあれば知識入れたいですので、それはそれでウェルカムです。

またこれは別ですが、色彩もバラバラになると思いますので、デフォルトでchakra-uiのテーマ色を入れるコンポーネントも追加しても良いかもしれません。

**Comment by london-newyork** [comment]
ディレクトリ構成について、お返事いただきありがとうございます！
確かにそうですよね！

確かに個々にコンポーネント追加していくと、色彩がバラバラになりそうですね。
chakra-uiのテーマ色を入れるコンポーネントというのは、私も不勉強でわかってないのですが、theme-color.jsみたいな形にして、色のみそこへ追加していく形ですかね。
他にも何か統一しなければならないものをそのファイルに入れたりしそうですか？
サイズとか・・

とりあえず、Chakura-uiの色彩をまとめるIssueを発行してみたいと思います。

**Comment by insideplant** [comment]
一旦atomicデザインにしておいて問題ないと思います。

また、themeについては、添付のページのようにextendThemeでカスタマイズして
デフォルトの背景、フォントサイズを設定する形になると思います。
https://chakra-ui.com/docs/theming/customize-theme

**Comment by london-newyork** [comment]
了解です。
一旦atomicデザインにしておき、問題出てくるようでしたらその時何か考える方向でお願いいたします。

themeについて、とりあえずいただいたURLを参照してファイルを作成していただくよう、Issueに含めます。
色々とありがとうございます！

**Comment by mihomihouk** [comment]
ディレクトリ構成についての議論に間に合わず申し訳ありません。
私もatomicデザインに則る方針に賛同します！atoms、moelcules、organismsとざっくり分類分けしていく方向で進めた方が、atomicデザインの学習にもなると同時に、混乱も少なく可読性もぐっと上がると思います！

extendTheme作成のissueの中で、グローバル要素を書き出したらぐっと作業が楽になりそうですね！

お2人ともありがとうございます！

**Comment by london-newyork** [comment]
mihoさん、ご理解いただきありがとうございます！
そうですね、Atomicデザイン自体、難しいですが勉強しておいて別に損ではなさそうな感じもしますね。
昔Sassのクラスの、atomicデザインに似たような分け方で流行ったのが、FLOCCSなどでした。これはこれで苦労したのですが、多分こういったatomicデザインのような分け方って、その時の流行で出てきたりするんだと思います。
