### ISSUE TITLE
【 UI 】[ Edit Todo (編集)] ページ内でコンポーネント化が必要な部分をコンポーネント化

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#64]
## 実装内容の説明
- Edit Todoページで新たにコンポーネント化が必要な部分について、コンポーネント作成をお願いいたします。
- 既に別のIssueやPR内で作成済みの子コンポーネントがありましたら、それを取り込み、親ページ(ページ全体のコンポーネント) へ反映をお願いいたします。
- 実装部分は図の赤枠内の「UI」のみになります。

## 実装予定のページ・コンポーネントのデザイン画像もしくはURL

![edit-todo-page](https://user-images.githubusercontent.com/57102971/149944739-2fb8d442-bd51-485c-b50e-0d62133c598a.png)

## TASK
- [ ] Edit Todoページで新たにコンポーネント化が必要な部分について、コンポーネントの作成。
- [ ] 既に別のIssueやPR内で作成済みの子コンポーネントがあれば取り込み、親ページ(ページ全体のコンポーネント) へ反映。

## その他・備考
- 必要のない作業
・EditTodoページ以外のページの実装

**Comment by mihomihouk** [comment]
@london-newyork 
ゆりさん、大変申し訳ありません。私の確認ミスで、一部のコンポーネントの読み込みに誤りがあったことに気が付かずマージを承認してしまったようです。すぐさま別ブランチを切って修正致します。

**Comment by london-newyork** [comment]
みほさん、いえいえ大丈夫です！
