### ISSUE TITLE
【 UI 】[ Show Todo (詳細)] ページ内でコンポーネント化が必要な部分をコンポーネント化と、コメント一覧＆ボタンの作成

### ISSUE THREAD

**Issue by london-newyork** [if-tech-support/todo_team_2#67]
## 実装内容の説明
- Show todoページで新たにコンポーネント化が必要な部分を見つけ出し、コンポーネント作成をお願いいたします。
- 既に別のIssueやPR内で作成済みの子コンポーネントがありましたら、それを取り込み、親ページ(ページ全体のコンポーネント) へ反映をお願いいたします。
- **Show todoページでは、コメントボタンと、コメント一覧の表示（ダミー）の実装もお願いいたします。**（※Issueの抜け漏れですm(_ _)m）

追記)コメント一覧は別Issueで作成しているのでした。ゴメンなさい。
- 実装部分は図の赤枠内の「UI」のみになります。

## 実装予定のページ・コンポーネントのデザイン画像もしくはURL

全体

![show-todo-page](https://user-images.githubusercontent.com/57102971/149952002-690dc5c7-1f6c-4ee3-a91f-0e2d86064d31.png)

**コメントボタンと、コメント一覧の表示（ダミー）部分**

![showtodo-commentbtn-commentlist](https://user-images.githubusercontent.com/57102971/150153250-0389239d-4474-42b4-89ba-14eafe6faeea.png)

## TASK
- [ ] Show Todoページで新たにコンポーネント化が必要な部分を見つけ出し、コンポーネントの作成。
- [ ] コメント一覧の実装
- [ ] コメントボタンの実装
- [ ] 既に別のIssueやPR内で作成済みの子コンポーネントがあれば取り込み、親ページ(ページ全体のコンポーネント) へ反映。

## その他・備考
- 必要のない作業
・Show Todoページ以外のページの実装

**Comment by nao5100000** [comment]
mihoさん修正ありがとうございます！
確認させていただきました。
バッチリだと思いますので、マージの方お願いいたします！
